[ -f /usr/local/etc/bash_completion ]
. /usr/local/etc/bash_completion

GIT_PS1_SHOWDIRTYSTATE=true

eval $(docker-machine env default)
eval $(thefuck --alias)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ashleigh/Downloads/google-cloud-sdk/path.bash.inc' ]; then source '/Users/ashleigh/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/ashleigh/Downloads/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/ashleigh/Downloads/google-cloud-sdk/completion.bash.inc'; fi

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\u@\h \W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "

export GPG_TTY=$(tty)

source ~/.aliases

neofetch